### ISSUE TITLE
yapf doesn't handle all flake8 errors

### ISSUE THREAD

**Issue by karx1** [The-Domecode/domecode-opensource#26]
The way yapf is currently set up, it only handles some of the flake8 errors. However, I believe I can get it to handle more of them. I'll be working on this over the next two days, so if you could assign this issue to me that would be great!

(paging @arthtyagi )

**Comment by arthtyagi** [comment]
You'll need to make all the final changes in one PR. No further PRs would be entertained on this issue.

**Comment by karx1** [comment]
Yeah, I only made this issue because the contributors guide said I need an
issue to make a PR. All the final changes will be in this PR, and then it
will be finished.

**Comment by arthtyagi** [comment]
sounds perfect!
