### ISSUE TITLE
Contributor's guide is not clear enough

### ISSUE THREAD

**Issue by karx1** [The-Domecode/domecode-opensource#33]
I will submit a PR for this- basically I just want to make it easier to get a working environment to work on domecode.

**Comment by arthtyagi** [comment]
To make the guide clearer means you'd need to include notes on several "Why(s)" of the guide. The environment setup is already clear enough. There is a `Pipfile` and a `requirements.txt` file in the repository. 
`requirements.txt` is for those who would like to work with something other than `pipenv`. 
You should consider working on issue #15 if that's the case and you want to make things more clear for the users as well as the contributors.
